version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webscraper-ppp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zirr6atcrxxy"
s3_prefix = "webscraper-ppp"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
